/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthSelectBusinessRouteImport } from './routes/_auth/select-business'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppMenuRouteImport } from './routes/_app/menu'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AuthOnboardingIndexRouteImport } from './routes/_auth/onboarding/index'
import { Route as AuthOnboardingStaffRouteImport } from './routes/_auth/onboarding/staff'
import { Route as AuthOnboardingReviewRouteImport } from './routes/_auth/onboarding/review'
import { Route as AuthOnboardingPaymentsRouteImport } from './routes/_auth/onboarding/payments'
import { Route as AuthOnboardingMenuRouteImport } from './routes/_auth/onboarding/menu'
import { Route as AuthOnboardingBusinessRouteImport } from './routes/_auth/onboarding/business'
import { Route as AppSettingsStaffRouteImport } from './routes/_app/settings/staff'
import { Route as AppSettingsReceiptRouteImport } from './routes/_app/settings/receipt'
import { Route as AppSettingsPaymentsRouteImport } from './routes/_app/settings/payments'
import { Route as AppSettingsKitchenPrintRouteImport } from './routes/_app/settings/kitchen-print'
import { Route as AppSettingsFloorsRouteImport } from './routes/_app/settings/floors'
import { Route as AppSettingsFeesRouteImport } from './routes/_app/settings/fees'
import { Route as AppSettingsDiscountsRouteImport } from './routes/_app/settings/discounts'
import { Route as AppSettingsBusinessRouteImport } from './routes/_app/settings/business'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSelectBusinessRoute = AuthSelectBusinessRouteImport.update({
  id: '/select-business',
  path: '/select-business',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AuthOnboardingIndexRoute = AuthOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingStaffRoute = AuthOnboardingStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingReviewRoute = AuthOnboardingReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingPaymentsRoute = AuthOnboardingPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingMenuRoute = AuthOnboardingMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingBusinessRoute = AuthOnboardingBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AppSettingsStaffRoute = AppSettingsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsReceiptRoute = AppSettingsReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPaymentsRoute = AppSettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsKitchenPrintRoute = AppSettingsKitchenPrintRouteImport.update({
  id: '/kitchen-print',
  path: '/kitchen-print',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsFloorsRoute = AppSettingsFloorsRouteImport.update({
  id: '/floors',
  path: '/floors',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsFeesRoute = AppSettingsFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDiscountsRoute = AppSettingsDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBusinessRoute = AppSettingsBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/menu': typeof AppMenuRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRouteWithChildren
  '/select-business': typeof AuthSelectBusinessRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/settings/business': typeof AppSettingsBusinessRoute
  '/settings/discounts': typeof AppSettingsDiscountsRoute
  '/settings/fees': typeof AppSettingsFeesRoute
  '/settings/floors': typeof AppSettingsFloorsRoute
  '/settings/kitchen-print': typeof AppSettingsKitchenPrintRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/settings/receipt': typeof AppSettingsReceiptRoute
  '/settings/staff': typeof AppSettingsStaffRoute
  '/onboarding/business': typeof AuthOnboardingBusinessRoute
  '/onboarding/menu': typeof AuthOnboardingMenuRoute
  '/onboarding/payments': typeof AuthOnboardingPaymentsRoute
  '/onboarding/review': typeof AuthOnboardingReviewRoute
  '/onboarding/staff': typeof AuthOnboardingStaffRoute
  '/onboarding/': typeof AuthOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/menu': typeof AppMenuRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/select-business': typeof AuthSelectBusinessRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/settings/business': typeof AppSettingsBusinessRoute
  '/settings/discounts': typeof AppSettingsDiscountsRoute
  '/settings/fees': typeof AppSettingsFeesRoute
  '/settings/floors': typeof AppSettingsFloorsRoute
  '/settings/kitchen-print': typeof AppSettingsKitchenPrintRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/settings/receipt': typeof AppSettingsReceiptRoute
  '/settings/staff': typeof AppSettingsStaffRoute
  '/onboarding/business': typeof AuthOnboardingBusinessRoute
  '/onboarding/menu': typeof AuthOnboardingMenuRoute
  '/onboarding/payments': typeof AuthOnboardingPaymentsRoute
  '/onboarding/review': typeof AuthOnboardingReviewRoute
  '/onboarding/staff': typeof AuthOnboardingStaffRoute
  '/onboarding': typeof AuthOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/menu': typeof AppMenuRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/onboarding': typeof AuthOnboardingRouteWithChildren
  '/_auth/select-business': typeof AuthSelectBusinessRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_app/settings/business': typeof AppSettingsBusinessRoute
  '/_app/settings/discounts': typeof AppSettingsDiscountsRoute
  '/_app/settings/fees': typeof AppSettingsFeesRoute
  '/_app/settings/floors': typeof AppSettingsFloorsRoute
  '/_app/settings/kitchen-print': typeof AppSettingsKitchenPrintRoute
  '/_app/settings/payments': typeof AppSettingsPaymentsRoute
  '/_app/settings/receipt': typeof AppSettingsReceiptRoute
  '/_app/settings/staff': typeof AppSettingsStaffRoute
  '/_auth/onboarding/business': typeof AuthOnboardingBusinessRoute
  '/_auth/onboarding/menu': typeof AuthOnboardingMenuRoute
  '/_auth/onboarding/payments': typeof AuthOnboardingPaymentsRoute
  '/_auth/onboarding/review': typeof AuthOnboardingReviewRoute
  '/_auth/onboarding/staff': typeof AuthOnboardingStaffRoute
  '/_auth/onboarding/': typeof AuthOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/menu'
    | '/reports'
    | '/settings'
    | '/login'
    | '/onboarding'
    | '/select-business'
    | '/verify-otp'
    | '/settings/business'
    | '/settings/discounts'
    | '/settings/fees'
    | '/settings/floors'
    | '/settings/kitchen-print'
    | '/settings/payments'
    | '/settings/receipt'
    | '/settings/staff'
    | '/onboarding/business'
    | '/onboarding/menu'
    | '/onboarding/payments'
    | '/onboarding/review'
    | '/onboarding/staff'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/menu'
    | '/reports'
    | '/settings'
    | '/login'
    | '/select-business'
    | '/verify-otp'
    | '/settings/business'
    | '/settings/discounts'
    | '/settings/fees'
    | '/settings/floors'
    | '/settings/kitchen-print'
    | '/settings/payments'
    | '/settings/receipt'
    | '/settings/staff'
    | '/onboarding/business'
    | '/onboarding/menu'
    | '/onboarding/payments'
    | '/onboarding/review'
    | '/onboarding/staff'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/menu'
    | '/_app/reports'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/onboarding'
    | '/_auth/select-business'
    | '/_auth/verify-otp'
    | '/_app/settings/business'
    | '/_app/settings/discounts'
    | '/_app/settings/fees'
    | '/_app/settings/floors'
    | '/_app/settings/kitchen-print'
    | '/_app/settings/payments'
    | '/_app/settings/receipt'
    | '/_app/settings/staff'
    | '/_auth/onboarding/business'
    | '/_auth/onboarding/menu'
    | '/_auth/onboarding/payments'
    | '/_auth/onboarding/review'
    | '/_auth/onboarding/staff'
    | '/_auth/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/select-business': {
      id: '/_auth/select-business'
      path: '/select-business'
      fullPath: '/select-business'
      preLoaderRoute: typeof AuthSelectBusinessRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/onboarding/': {
      id: '/_auth/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthOnboardingIndexRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/staff': {
      id: '/_auth/onboarding/staff'
      path: '/staff'
      fullPath: '/onboarding/staff'
      preLoaderRoute: typeof AuthOnboardingStaffRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/review': {
      id: '/_auth/onboarding/review'
      path: '/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof AuthOnboardingReviewRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/payments': {
      id: '/_auth/onboarding/payments'
      path: '/payments'
      fullPath: '/onboarding/payments'
      preLoaderRoute: typeof AuthOnboardingPaymentsRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/menu': {
      id: '/_auth/onboarding/menu'
      path: '/menu'
      fullPath: '/onboarding/menu'
      preLoaderRoute: typeof AuthOnboardingMenuRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/business': {
      id: '/_auth/onboarding/business'
      path: '/business'
      fullPath: '/onboarding/business'
      preLoaderRoute: typeof AuthOnboardingBusinessRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_app/settings/staff': {
      id: '/_app/settings/staff'
      path: '/staff'
      fullPath: '/settings/staff'
      preLoaderRoute: typeof AppSettingsStaffRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/receipt': {
      id: '/_app/settings/receipt'
      path: '/receipt'
      fullPath: '/settings/receipt'
      preLoaderRoute: typeof AppSettingsReceiptRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/payments': {
      id: '/_app/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof AppSettingsPaymentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/kitchen-print': {
      id: '/_app/settings/kitchen-print'
      path: '/kitchen-print'
      fullPath: '/settings/kitchen-print'
      preLoaderRoute: typeof AppSettingsKitchenPrintRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/floors': {
      id: '/_app/settings/floors'
      path: '/floors'
      fullPath: '/settings/floors'
      preLoaderRoute: typeof AppSettingsFloorsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/fees': {
      id: '/_app/settings/fees'
      path: '/fees'
      fullPath: '/settings/fees'
      preLoaderRoute: typeof AppSettingsFeesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/discounts': {
      id: '/_app/settings/discounts'
      path: '/discounts'
      fullPath: '/settings/discounts'
      preLoaderRoute: typeof AppSettingsDiscountsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/business': {
      id: '/_app/settings/business'
      path: '/business'
      fullPath: '/settings/business'
      preLoaderRoute: typeof AppSettingsBusinessRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsBusinessRoute: typeof AppSettingsBusinessRoute
  AppSettingsDiscountsRoute: typeof AppSettingsDiscountsRoute
  AppSettingsFeesRoute: typeof AppSettingsFeesRoute
  AppSettingsFloorsRoute: typeof AppSettingsFloorsRoute
  AppSettingsKitchenPrintRoute: typeof AppSettingsKitchenPrintRoute
  AppSettingsPaymentsRoute: typeof AppSettingsPaymentsRoute
  AppSettingsReceiptRoute: typeof AppSettingsReceiptRoute
  AppSettingsStaffRoute: typeof AppSettingsStaffRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBusinessRoute: AppSettingsBusinessRoute,
  AppSettingsDiscountsRoute: AppSettingsDiscountsRoute,
  AppSettingsFeesRoute: AppSettingsFeesRoute,
  AppSettingsFloorsRoute: AppSettingsFloorsRoute,
  AppSettingsKitchenPrintRoute: AppSettingsKitchenPrintRoute,
  AppSettingsPaymentsRoute: AppSettingsPaymentsRoute,
  AppSettingsReceiptRoute: AppSettingsReceiptRoute,
  AppSettingsStaffRoute: AppSettingsStaffRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMenuRoute: typeof AppMenuRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMenuRoute: AppMenuRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthOnboardingRouteChildren {
  AuthOnboardingBusinessRoute: typeof AuthOnboardingBusinessRoute
  AuthOnboardingMenuRoute: typeof AuthOnboardingMenuRoute
  AuthOnboardingPaymentsRoute: typeof AuthOnboardingPaymentsRoute
  AuthOnboardingReviewRoute: typeof AuthOnboardingReviewRoute
  AuthOnboardingStaffRoute: typeof AuthOnboardingStaffRoute
  AuthOnboardingIndexRoute: typeof AuthOnboardingIndexRoute
}

const AuthOnboardingRouteChildren: AuthOnboardingRouteChildren = {
  AuthOnboardingBusinessRoute: AuthOnboardingBusinessRoute,
  AuthOnboardingMenuRoute: AuthOnboardingMenuRoute,
  AuthOnboardingPaymentsRoute: AuthOnboardingPaymentsRoute,
  AuthOnboardingReviewRoute: AuthOnboardingReviewRoute,
  AuthOnboardingStaffRoute: AuthOnboardingStaffRoute,
  AuthOnboardingIndexRoute: AuthOnboardingIndexRoute,
}

const AuthOnboardingRouteWithChildren = AuthOnboardingRoute._addFileChildren(
  AuthOnboardingRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRouteWithChildren
  AuthSelectBusinessRoute: typeof AuthSelectBusinessRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRouteWithChildren,
  AuthSelectBusinessRoute: AuthSelectBusinessRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
